### ISSUE TITLE
[question] How to create `aedes` broker cluster in Docker?

### ISSUE THREAD

**Issue by tukusejssirs** [moscajs/aedes-cli#152]
First asked on [SO](https://stackoverflow.com/questions/71945723/how-to-create-aedes-broker-cluster-in-docker).

---

I need to create a MQTT broker cluster. I want to use `aedes` (as I already use it, albeit without cluster) and Docker. Note that I have never created a cluster before (with nor without Docker).

[Here](https://github.com/moscajs/aedes/blob/main/examples/clusters/index.js) I found official example how to create a cluster using `aedes`, but I was thinking about using [`aedes-cli`](https://hub.docker.com/r/moscajs/aedes) Docker image.

Now, I have no idea which is better: should I create separate containers per broker (similarly to [this question](https://stackoverflow.com/questions/67952623/redis-cluster-on-docker-compose-with-network-mode-host-unable-to-connect-to-re)) or use `mqemitter-redis`/`mqemitter-mongodb` (as the [`aedes-cli` docs](https://github.com/moscajs/aedes-cli#persistence-and-emitters) suggest).

As for creating separate containers, I have no idea how to connect them.

As for using `mqemitter-redis`/`mqemitter-mongodb`, I have no idea how to setup them in the `aedes-cli` config file.

I have no need for data persistance accross broker cluster restarts. All I need is to distribute the messages accross multiple brokers in order to improve the runtime performance.

---

Below is a working, single-broker configuration.

- `aedes.yml`:

```yaml
version: '3.7'
services:
  aedes:
    container_name: aedes
    image: moscajs/aedes:latest
    restart: always
    stop_signal: SIGINT
    network_mode: host
    command: -c /data/dockerConfig.js
    volumes:
      - /some/path/mqtt:/data
  mongo:
    container_name: mongo
    restart: always
    network_mode: host
    logging:
      driver: none
    image: mvertes/alpine-mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
volumes:
  mongo_data:
    name: mongo_data
```

- `/some/path/mqtt/dockerConfig.js`

```js
module.exports = {
  protos: ['tcp', 'ws'],
  host: 'localhost',
  port: 1883,
  wsPort: 3000,
  wssPort: 4000,
  tlsPort: 8883,
  key: null,
  cert: null,
  rejectUnauthorized: true,
  credentials: null,
  brokerId: 'aedes',
  concurrency: 100,
  queueLimit: 42,
  maxClientsIdLength: 23,
  heartbeatInterval: 60000,
  connectTimeout: 30000,
  stats: false,
  statsInterval: 5000,
  mq: {
    name: 'mongodb',
    options: {
      url: 'mongodb://localhost:27017/aedes'
    }
  },
  verbose: false,
  veryVerbose: false,
  noPretty: false
}
```

**Comment by robertsLando** [comment]
the configuration you used is correct but you also need to setup mongodb/redis persistence. mqemitter is used to share messages between aedes instances and mongo to persist qos > 0, retained messages and subscriptions so you also need that.

**Comment by tukusejssirs** [comment]
@robertsLando, thanks for reply! :pray:

I don’t need persistence nor QOS > 0. Do I still need to setup `persistence`? All I need to have a cluster and to enable the communication between cluster nodes/brokers.

As for the main question: as I understand it, the config in the OP is not yet a cluster config, is it? If it is not a cluster yet, how to make a cluster config?
- Should I create a Docker container per cluster node/broker? How could I make the brokers communicate with each other?
- If I should go for config like [this](https://github.com/moscajs/aedes/blob/main/examples/clusters/index.js), how can I do this using `aedes-cli` in Docker container?

**Comment by robertsLando** [comment]
You should setup both mqemitter and persistence in order to run clusters

Then follow this guide to provide the load balancing: https://pspdfkit.com/blog/2018/how-to-use-docker-compose-to-run-multiple-instances-of-a-service-in-development/

**Comment by tukusejssirs** [comment]
Thanks again. The linked site help me a lot, however, the ports (`port`, `wsPort`, `wssPort`, `tlsPort`) collide. Only once container instance runs successfully, others fail with `EADDRINUSE` (obviously). See below my current config. I think the culprit is that currently I need to use `network_mode` set to `host` (all I actually need is to access the broker from on host itself, as my app is not yet running in Docker).

Is there a way to change the ports per container instance? Or how could I work around the issue?


- `aedes.yml`:

```yaml
version: '3.7'
services:
  aedes:
    # Note: I needed to remove `container_name`, as each container instance needs to have different name.
    # container_name: aedes
    image: moscajs/aedes:latest
    restart: always
    stop_signal: SIGINT
    scale: 3
    network_mode: host
    command: -c /data/dockerConfig.js
    volumes:
      - /some/path/mqtt:/data
  mongo:
    container_name: mongo
    restart: always
    network_mode: host
    logging:
      driver: none
    image: mvertes/alpine-mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
volumes:
  mongo_data:
    name: mongo_data
```

- `/some/path/mqtt/dockerConfig.js`

```js
module.exports = {
  protos: ['tcp', 'ws'],
  host: 'localhost',
  port: 1883,
  wsPort: 3000,
  wssPort: 4000,
  tlsPort: 8883,
  key: null,
  cert: null,
  rejectUnauthorized: true,
  credentials: null,
  brokerId: 'aedes',
  concurrency: 100,
  queueLimit: 42,
  maxClientsIdLength: 23,
  heartbeatInterval: 60000,
  connectTimeout: 30000,
  stats: false,
  statsInterval: 5000,
  persistence: {
    name: 'mongodb',
    options: {
      url: 'mongodb://localhost:27017/aedes'
    }
  },
  mq: {
    name: 'mongodb',
    options: {
      url: 'mongodb://localhost:27017/aedes'
    }
  },
  verbose: false,
  veryVerbose: false,
  noPretty: false
}
```
