### ISSUE TITLE
[bug] Persistence MongoDB is not working

### ISSUE THREAD

**Issue by iwillflytothemoon** [moscajs/aedes-cli#34]
**System Information**
- Aedes-cli: latest
- NodeJS: 14.5.0
- OS: Alpine 3.11.6
- Arch: x86_64

**Describe the bug**
![image](https://user-images.githubusercontent.com/6613339/88506442-8226fe80-d00c-11ea-9535-63e903cdac5e.png)

**To Reproduce**
1. Run the docker-compose.yaml file
2. See error

**Expected behavior**
Aedes container should be running ok with Mongodb connection.

**Additional context**
config.js
```
module.exports = {
  // SERVERS
  protos: ['tcp'],
  host: '0.0.0.0',
  port: 1883,
  wsPort: 3000,
  wssPort: 4000,
  tlsPort: 8883,
  key: null,
  cert: null,
  rejectUnauthorized: false,
  // AUTHORIZER
  credentials: '/data/credentials.json',
  // AEDES
  brokerId: 'aedes-cli',
  concurrency: 100,
  queueLimit: 42,
  maxClientsIdLength: 23,
  heartbeatInterval: 60000,
  connectTimeout: 30000,
  stats: true,
  statsInterval: 5000,
  // PERSISTENCES
  persistence: {
    name: 'mongodb',
    options: {
      url: 'mongodb://127.0.0.1/aedes'
    }
  },
  mq: null,
  // LOGGER
  verbose: true,
  veryVerbose: false,
  noPretty: false
}
```
docker-compose.yaml
```
version: '3.7'
services:
 aedes:
   container_name: aedes
   image: i/aedes:latest
   restart: always
   stop_signal: SIGINT
   networks:
     - mqtt
   command: --config /data/config-persistent.js --credentials /data/credentials.json # add here the options to pass to aedes
   volumes:
     - ./:/data # map the local folder to aedes
   ports:
     - '1884:1883'
     - '3001:3000'
     - '4001:4000'
     - '8884:8883'
 mongo:
   container_name: mongo
   networks:
     - mqtt
   logging:
     driver: none
   image: mvertes/alpine-mongo
   volumes:
     - db-data:/data/db
   ports:
     - "27018:27017"
volumes:
 db-data:
   name: db-data
networks:
 mqtt:
```

I created my own image since the image from docker-hub is not working.
