### ISSUE TITLE
[question] Persistence Redis setup

### ISSUE THREAD

**Issue by iwillflytothemoon** [moscajs/aedes-cli#58]
I receved an error after trying to setup redis persistence. Here's the error I received.
![image](https://user-images.githubusercontent.com/6613339/93735573-e383dc00-fc0f-11ea-8110-bf117fbe80a1.png)

My docker-compose.yaml:
```
version: '3.7'
services:
  aedes-1:
    container_name: aedes-1
    image: i/aedes:latest
    restart: always
    stop_signal: SIGINT
    networks:
      - mqtt
    command: --config /data/config-persistent.js --credentials /data/credentials.json # add here the options to pass to aedes
    volumes:
      - ./:/data # map the local folder to aedes
    ports:
      - '1884:1883'
      - '8884:8883'
  # mongo:
  #   container_name: mongo
  #   networks:
  #     - mqtt
  #   logging:
  #     driver: none
  #   image: mvertes/alpine-mongo
  #   volumes:
  #     - db-data:/data/db
  #   ports:
  #     - "27018:27017"
  redis:
    container_name: redis
    networks:
      - mqtt
    logging:
      driver: none
    image: redis:6-alpine
    volumes:
      - db-data:/data/redis
    ports:
      - "6379:6379"
volumes:
  db-data:
    name: db-data
networks:
  mqtt:
```

and my config-persistent.js:
```
module.exports = {
  // SERVERS
  protos: ['tcp'],
  host: '0.0.0.0',
  port: 1883,
  wsPort: 3000,
  wssPort: 4000,
  tlsPort: 8883,
  key: null,
  cert: null,
  rejectUnauthorized: false,
  // AUTHORIZER
  credentials: '/data/credentials.json',
  // AEDES
  brokerId: 'aedes-cli',
  concurrency: 100,
  queueLimit: 42,
  maxClientsIdLength: 23,
  heartbeatInterval: 60000,
  connectTimeout: 30000,
  stats: true,
  statsInterval: 5000,
  // PERSISTENCES
  persistence: {
    name: 'redis',
    options: {
      url: 'redis'
    }
  },
  mq: null,
  verbose: false,
  veryVerbose: false,
  noPretty: false
}
```
